// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package users is a generated GoMock package.
package users

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// Mockrepository is a mock of repository interface.
type Mockrepository struct {
	ctrl     *gomock.Controller
	recorder *MockrepositoryMockRecorder
}

// MockrepositoryMockRecorder is the mock recorder for Mockrepository.
type MockrepositoryMockRecorder struct {
	mock *Mockrepository
}

// NewMockrepository creates a new mock instance.
func NewMockrepository(ctrl *gomock.Controller) *Mockrepository {
	mock := &Mockrepository{ctrl: ctrl}
	mock.recorder = &MockrepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepository) EXPECT() *MockrepositoryMockRecorder {
	return m.recorder
}

// checkUserExists mocks base method.
func (m *Mockrepository) checkUserExists(ctx context.Context, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "checkUserExists", ctx, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// checkUserExists indicates an expected call of checkUserExists.
func (mr *MockrepositoryMockRecorder) checkUserExists(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "checkUserExists", reflect.TypeOf((*Mockrepository)(nil).checkUserExists), ctx, username)
}

// createUser mocks base method.
func (m *Mockrepository) createUser(ctx context.Context, params CreateUserDTO) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "createUser", ctx, params)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// createUser indicates an expected call of createUser.
func (mr *MockrepositoryMockRecorder) createUser(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "createUser", reflect.TypeOf((*Mockrepository)(nil).createUser), ctx, params)
}

// enableUser mocks base method.
func (m *Mockrepository) enableUser(ctx context.Context, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "enableUser", ctx, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// enableUser indicates an expected call of enableUser.
func (mr *MockrepositoryMockRecorder) enableUser(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "enableUser", reflect.TypeOf((*Mockrepository)(nil).enableUser), ctx, username)
}

// getUserByEmail mocks base method.
func (m *Mockrepository) getUserByEmail(ctx context.Context, email string) (UserDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getUserByEmail", ctx, email)
	ret0, _ := ret[0].(UserDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getUserByEmail indicates an expected call of getUserByEmail.
func (mr *MockrepositoryMockRecorder) getUserByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getUserByEmail", reflect.TypeOf((*Mockrepository)(nil).getUserByEmail), ctx, email)
}

// getUserByUsername mocks base method.
func (m *Mockrepository) getUserByUsername(ctx context.Context, username string) (UserDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getUserByUsername", ctx, username)
	ret0, _ := ret[0].(UserDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getUserByUsername indicates an expected call of getUserByUsername.
func (mr *MockrepositoryMockRecorder) getUserByUsername(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getUserByUsername", reflect.TypeOf((*Mockrepository)(nil).getUserByUsername), ctx, username)
}

// updateUser mocks base method.
func (m *Mockrepository) updateUser(ctx context.Context, dto UpdateUserDTO) (UserDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "updateUser", ctx, dto)
	ret0, _ := ret[0].(UserDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// updateUser indicates an expected call of updateUser.
func (mr *MockrepositoryMockRecorder) updateUser(ctx, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "updateUser", reflect.TypeOf((*Mockrepository)(nil).updateUser), ctx, dto)
}
